# Generated by Django 2.1 on 2022-04-23 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20220423_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
