# Generated by Django 2.1 on 2022-04-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20220423_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='aval_time',
            new_name='available_time',
        ),
    ]
