# Generated by Django 2.1 on 2022-04-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_auto_20220423_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
