# Generated by Django 2.1 on 2022-04-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_auto_20220423_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
