# Generated by Django 2.1 on 2022-04-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_auto_20220423_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='available_time',
            field=models.DateTimeField(null=True),
        ),
    ]
