# Generated by Django 2.1 on 2022-04-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0010_auto_20220423_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='username',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='dob',
            field=models.DateField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
