# Generated by Django 2.1 on 2022-04-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0011_auto_20220423_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='hospital',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
