# Generated by Django 2.1 on 2022-04-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0013_donor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='height',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='weight',
            field=models.DecimalField(decimal_places=5, max_digits=5, null=True),
        ),
    ]
