# Generated by Django 2.1 on 2022-04-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0016_auto_20220425_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='dob',
            field=models.DateField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
