# Generated by Django 2.1 on 2022-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0017_auto_20220425_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='height',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='weight',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
