# Generated by Django 2.1 on 2022-04-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0018_auto_20220427_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='height',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='weight',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
