# Generated by Django 4.0.4 on 2022-04-28 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0019_auto_20220427_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
