# Generated by Django 2.1 on 2022-05-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0020_alter_donor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
