# Generated by Django 4.0.4 on 2022-05-03 11:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0022_donor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
