# Generated by Django 4.0.4 on 2022-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0024_remove_donor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='hospital',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
