# Generated by Django 4.0.4 on 2022-05-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0025_alter_donor_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.AddField(
            model_name='donor',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
