# Generated by Django 4.0.4 on 2022-05-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0026_remove_donor_user_donor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
