# Generated by Django 2.1 on 2022-05-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_donor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
