# Generated by Django 2.1 on 2022-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
