# Generated by Django 2.1 on 2022-04-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20220427_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='password',
        ),
    ]
