# Generated by Django 2.1 on 2022-04-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_hospital_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='password',
            field=models.CharField(help_text='Use  \'[algo]$[salt]$[hexdigest]\' or use the <a href="password/">change password form</a>.', max_length=128, null=True, verbose_name='password'),
        ),
    ]
