# Generated by Django 2.1 on 2022-04-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospital_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
