# Generated by Django 2.1 on 2022-05-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_hospital_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='username',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
