# Generated by Django 2.1 on 2022-05-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_hosp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosp',
            old_name='email',
            new_name='hi',
        ),
    ]
