# Generated by Django 2.1 on 2022-05-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_auto_20220502_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hosp',
            new_name='Trial',
        ),
    ]
