# Generated by Django 2.1 on 2022-05-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20220502_1752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trial',
        ),
    ]
