# Generated by Django 2.1 on 2022-05-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_delete_trial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
